messages:
    type:     rest
    resource: @MessengerBundle/Controller/MessagesController.php
    prefix: messages

conversations:
    type:     rest
    resource: @MessengerBundle/Controller/ConversationsController.php
